import type { Career } from "./careers-types";

export const EXTRA_CAREERS: Omit<Career, "field">[] = [
  {
    id: "civil-eng",
    name: "Kỹ sư xây dựng",
    tagline: "Thiết kế và giám sát công trình",
    highlight: "Ổn định",
    description: "Lập thiết kế kết cấu, giám sát thi công nhà ở, cầu đường, hạ tầng đô thị.",
    skills: ["AutoCAD", "Quản lý dự án", "Toán", "An toàn công trình"],
    averageSalary: "12–40 triệu/tháng (VN)",
    relatedSubjects: ["Toán", "Vật lý", "Tin học"],
    opportunities: ["Tổng thầu", "Tư vấn thiết kế", "Bất động sản"],
    workEnvironment: "Công trường, văn phòng tư vấn, tập đoàn xây dựng",
    studyPath: "Xây dựng · Kiến trúc · Quản lý xây dựng",
  },
  {
    id: "elec-eng",
    name: "Kỹ sư điện – điện tử",
    tagline: "Thiết kế hệ thống điện và linh kiện",
    description: "Phát triển mạch điện, thiết bị điện tử, hệ thống năng lượng và tự động hoá.",
    skills: ["Mạch điện", "Lập trình nhúng", "Vật lý", "Troubleshooting"],
    averageSalary: "12–38 triệu/tháng (VN)",
    relatedSubjects: ["Vật lý", "Toán", "Tin học"],
    opportunities: ["Semiconductor", "IoT", "Năng lượng", "Ô tô điện"],
    workEnvironment: "Nhà máy, lab R&D, công ty điện tử",
    studyPath: "Điện – Điện tử · Điện tử viễn thông",
  },
  {
    id: "pharm",
    name: "Dược sĩ",
    tagline: "Tư vấn thuốc và an toàn dược phẩm",
    highlight: "Ổn định",
    description: "Kiểm soát thuốc, tư vấn liều lượng, phát triển sản phẩm dược tại nhà thuốc hoặc công ty.",
    skills: ["Hoá sinh", "Tư vấn", "Tỉ mỉ", "Giao tiếp"],
    averageSalary: "10–30 triệu/tháng (VN)",
    relatedSubjects: ["Hoá", "Sinh học", "Toán"],
    opportunities: ["Nhà thuốc", "Công ty dược", "QC/QA dược"],
    workEnvironment: "Bệnh viện, nhà thuốc, nhà máy dược",
    studyPath: "Dược · Dược sĩ đại học",
  },
  {
    id: "dentist",
    name: "Nha sĩ",
    tagline: "Chăm sóc răng miệng và thẩm mỹ nụ cười",
    description: "Khám, điều trị răng, chỉnh nha, phục hình và tư vấn vệ sinh răng miệng.",
    skills: ["Khéo tay", "Kiên nhẫn", "Sinh học", "Giao tiếp"],
    averageSalary: "15–60+ triệu/tháng (tuỳ phòng khám)",
    relatedSubjects: ["Sinh học", "Hoá", "Toán"],
    opportunities: ["Phòng khám tư", "Bệnh viện", "Chỉnh nha"],
    workEnvironment: "Phòng khám nha khoa, bệnh viện",
    studyPath: "Răng hàm mặt · Chứng chỉ chuyên khoa",
  },
  {
    id: "vet",
    name: "Bác sĩ thú y",
    tagline: "Chăm sóc sức khoẻ động vật",
    description: "Khám chữa bệnh cho thú cưng, gia súc; tư vấn dinh dưỡng và phòng dịch.",
    skills: ["Sinh học", "Đồng cảm", "Quan sát", "Giao tiếp"],
    averageSalary: "8–25 triệu/tháng (VN)",
    relatedSubjects: ["Sinh học", "Hoá"],
    opportunities: ["Phòng khám thú y", "Trang trại", "Pet care chain"],
    workEnvironment: "Phòng khám, trang trại, công ty thức ăn chăn nuôi",
    studyPath: "Thú y · Cao đẳng/Đại học thú y",
  },
  {
    id: "psych",
    name: "Chuyên viên tâm lý",
    tagline: "Đồng hành cảm xúc và hành vi",
    highlight: "Hot",
    description: "Tư vấn tâm lý học đường, lâm sàng hoặc tổ chức; hỗ trợ stress, lo âu, định hướng.",
    skills: ["Lắng nghe", "Đồng cảm", "Phân tích", "Bảo mật"],
    averageSalary: "10–35 triệu/tháng (VN)",
    relatedSubjects: ["Sinh học", "Ngữ văn", "GDCD"],
    opportunities: ["Trường học", "Phòng khám", "Doanh nghiệp", "Online counseling"],
    workEnvironment: "Trung tâm tư vấn, trường học, bệnh viện",
    studyPath: "Tâm lý học · Cao học tâm lý lâm sàng",
  },
  {
    id: "journalist",
    name: "Nhà báo / Phóng viên",
    tagline: "Kể chuyện và giữ tiếng nói công chúng",
    description: "Điều tra, viết bài, quay phim tin tức cho báo, online, truyền hình.",
    skills: ["Viết lách", "Phỏng vấn", "Fact-check", "Deadline"],
    averageSalary: "8–25 triệu/tháng (VN)",
    relatedSubjects: ["Ngữ văn", "Lịch sử", "Tiếng Anh"],
    opportunities: ["Báo điện tử", "Truyền hình", "Creator news"],
    workEnvironment: "Redaction, hiện trường, remote",
    studyPath: "Báo chí · Truyền thông đa phương tiện",
  },
  {
    id: "translator",
    name: "Biên – Phiên dịch viên",
    tagline: "Kết nối ngôn ngữ và văn hoá",
    description: "Dịch tài liệu, phiên dịch hội nghị, localization cho phần mềm và media.",
    skills: ["Tiếng Anh", "Viết", "Chuyên ngành", "Tỉ mỉ"],
    averageSalary: "10–35 triệu/tháng (VN)",
    relatedSubjects: ["Tiếng Anh", "Ngữ văn", "Văn hoá"],
    opportunities: ["Freelance", "Công ty dịch", "Game/app localization"],
    workEnvironment: "Remote, văn phòng, sự kiện",
    studyPath: "Ngôn ngữ Anh · Biên phiên dịch · Chứng chỉ IELTS/TOPIK",
  },
  {
    id: "hr",
    name: "Nhân sự",
    tagline: "Tuyển dụng và phát triển con người",
    description: "Recruitment, đào tạo, chính sách lương thưởng, văn hoá doanh nghiệp.",
    skills: ["Giao tiếp", "Đánh giá", "Tổ chức", "Empathy"],
    averageSalary: "10–30 triệu/tháng (VN)",
    relatedSubjects: ["Ngữ văn", "Kinh tế", "GDCD"],
    opportunities: ["HRBP", "Talent acquisition", "L&D"],
    workEnvironment: "Corporate, startup, HR agency",
    studyPath: "Quản trị nhân lực · Tâm lý · MBA (tuỳ mục tiêu)",
  },
  {
    id: "sales",
    name: "Chuyên viên kinh doanh",
    tagline: "Kết nối sản phẩm với khách hàng",
    highlight: "Thu nhập biến động cao",
    description: "Tìm kiếm khách hàng, chốt deal B2B/B2C, chăm sóc quan hệ và đạt target.",
    skills: ["Thuyết phục", "Lắng nghe", "Kiên trì", "CRM"],
    averageSalary: "8–50+ triệu/tháng (có hoa hồng)",
    relatedSubjects: ["Ngữ văn", "Kinh tế", "Tiếng Anh"],
    opportunities: ["SaaS", "Bất động sản", "FMCG", "Tech sales"],
    workEnvironment: "Văn phòng, gặp khách, hybrid",
    studyPath: "Marketing · Kinh doanh · Sales training on-job",
  },
  {
    id: "finance",
    name: "Chuyên viên tài chính",
    tagline: "Quản lý dòng tiền và đầu tư",
    description: "Phân tích báo cáo tài chính, lập ngân sách, đánh giá rủi ro cho doanh nghiệp.",
    skills: ["Excel", "Phân tích", "Mô hình tài chính", "Tiếng Anh"],
    averageSalary: "12–45 triệu/tháng (VN)",
    relatedSubjects: ["Toán", "Kinh tế", "Tin học"],
    opportunities: ["Corporate finance", "Investment", "Banking"],
    workEnvironment: "Ngân hàng, công ty niêm yết, quỹ",
    studyPath: "Tài chính · Kế toán · CFA/FRM (tuỳ mục tiêu)",
  },
  {
    id: "banker",
    name: "Nhân viên ngân hàng",
    tagline: "Dịch vụ tài chính cho cá nhân và doanh nghiệp",
    description: "Tư vấn vay, tiết kiệm, thẻ, sản phẩm bancassurance tại quầy hoặc RM.",
    skills: ["Giao tiếp", "Tư vấn", "Compliance", "Bán hàng"],
    averageSalary: "10–35 triệu/tháng (VN)",
    relatedSubjects: ["Toán", "Kinh tế", "Tiếng Anh"],
    opportunities: ["Retail banking", "Corporate banking", "Fintech"],
    workEnvironment: "Chi nhánh ngân hàng, văn phòng",
    studyPath: "Tài chính – Ngân hàng · Chứng chỉ nghiệp vụ ngân hàng",
  },
  {
    id: "real-estate",
    name: "Môi giới bất động sản",
    tagline: "Kết nối người mua – người bán nhà đất",
    description: "Tư vấn dự án, dẫn khách xem nhà, đàm phán và hỗ trợ pháp lý cơ bản.",
    skills: ["Thuyết phục", "Networking", "Am hiểu thị trường", "Kiên trì"],
    averageSalary: "Thu nhập chủ yếu hoa hồng · 10–100+ triệu/tháng",
    relatedSubjects: ["Kinh tế", "Địa lý", "Ngữ văn"],
    opportunities: ["Dự án căn hộ", "Đất nền", "Cho thuê văn phòng"],
    workEnvironment: "Sàn BĐS, đại lý, freelance",
    studyPath: "Kinh tế · Chứng chỉ môi giới BĐS",
  },
  {
    id: "chef",
    name: "Đầu bếp",
    tagline: "Sáng tạo ẩm thực và vận hành bếp",
    description: "Thiết kế menu, chế biến món ăn, quản lý bếp nhà hàng hoặc khách sạn.",
    skills: ["Khéo tay", "Sáng tạo", "Quản lý thời gian", "Vệ sinh ATTP"],
    averageSalary: "8–40 triệu/tháng (tuỳ level)",
    relatedSubjects: ["Hoá", "Sinh học", "GDCD"],
    opportunities: ["Fine dining", "Resort", "Cloud kitchen", "Food creator"],
    workEnvironment: "Nhà hàng, khách sạn, catering",
    studyPath: "Nghề bếp · Cao đẳng/Trung cấp ẩm thực",
  },
  {
    id: "hotel",
    name: "Quản lý khách sạn / Du lịch",
    tagline: "Trải nghiệm lưu trú và dịch vụ khách hàng",
    description: "Điều hành lễ tân, buồng phòng, F&B; thiết kế tour và trải nghiệm du lịch.",
    skills: ["Giao tiếp", "Tiếng Anh", "Tổ chức", "Giải quyết khiếu nại"],
    averageSalary: "8–35 triệu/tháng (VN)",
    relatedSubjects: ["Tiếng Anh", "Địa lý", "Ngữ văn"],
    opportunities: ["Resort", "OTA", "Tour operator", "Airline service"],
    workEnvironment: "Khách sạn, sân bay, công ty du lịch",
    studyPath: "Quản trị khách sạn · Du lịch",
  },
  {
    id: "fashion",
    name: "Thiết kế thời trang",
    tagline: "Biến ý tưởng thành sản phẩm mặc",
    highlight: "Sáng tạo",
    description: "Phác thảo, chọn vải, dựng rập, phối màu và phát triển bộ sưu tập.",
    skills: ["Vẽ", "May mẫu", "Trend research", "Thẩm mỹ"],
    averageSalary: "8–30 triệu/tháng (VN)",
    relatedSubjects: ["Mỹ thuật", "Hoá", "Tiếng Anh"],
    opportunities: ["Brand nội địa", "Freelance", "E-commerce fashion"],
    workEnvironment: "Xưởng may, studio, brand house",
    studyPath: "Thiết kế thời trang · May vá chuyên nghiệp",
  },
  {
    id: "interior",
    name: "Thiết kế nội thất",
    tagline: "Biến không gian thành nơi sống đẹp",
    description: "Layout phòng, chọn vật liệu, ánh sáng, nội thất cho nhà ở và văn phòng.",
    skills: ["3D", "CAD", "Thẩm mỹ", "Quản lý nhà thầu"],
    averageSalary: "10–35 triệu/tháng (VN)",
    relatedSubjects: ["Mỹ thuật", "Toán", "Vật lý"],
    opportunities: ["Studio nội thất", "Furniture brand", "Freelance"],
    workEnvironment: "Studio, công trường, showroom",
    studyPath: "Kiến trúc nội thất · Thiết kế đồ hoạ 3D",
  },
  {
    id: "game-dev",
    name: "Lập trình viên game",
    tagline: "Xây thế giới ảo và gameplay",
    highlight: "Hot",
    description: "Code gameplay, engine, multiplayer; tối ưu hiệu năng cho mobile/PC/console.",
    skills: ["C#/C++", "Unity/Unreal", "Logic", "Làm việc nhóm"],
    averageSalary: "15–50 triệu/tháng (VN)",
    relatedSubjects: ["Tin học", "Toán", "Tiếng Anh"],
    opportunities: ["Mobile game", "Outsource", "Indie studio"],
    workEnvironment: "Game studio, remote",
    studyPath: "CNTT · Game dev bootcamp + portfolio",
  },
  {
    id: "game-art",
    name: "Họa sĩ game / 3D",
    tagline: "Tạo nhân vật và thế giới game",
    description: "Concept art, model 3D, texture, animation cho game và metaverse.",
    skills: ["Blender/Maya", "Photoshop", "Thẩm mỹ", "Pipeline"],
    averageSalary: "12–40 triệu/tháng (VN)",
    relatedSubjects: ["Mỹ thuật", "Tin học"],
    opportunities: ["Game studio", "Animation", "Freelance"],
    workEnvironment: "Studio, remote",
    studyPath: "Mỹ thuật · Khóa 3D/game art",
  },
  {
    id: "cybersec",
    name: "Chuyên gia an ninh mạng",
    tagline: "Bảo vệ hệ thống khỏi tấn công",
    highlight: "Hot",
    description: "Pentest, SOC, incident response, bảo mật ứng dụng và hạ tầng cloud.",
    skills: ["Networking", "Linux", "Scripting", "Tư duy tấn công/phòng thủ"],
    averageSalary: "18–55 triệu/tháng (VN)",
    relatedSubjects: ["Tin học", "Toán", "Tiếng Anh"],
    opportunities: ["SOC", "Consulting", "Bug bounty"],
    workEnvironment: "Bank, fintech, MSSP, remote",
    studyPath: "An toàn thông tin · CEH/OSCP (tuỳ mục tiêu)",
  },
  {
    id: "devops",
    name: "Kỹ sư DevOps / Đám mây",
    tagline: "Vận hành hệ thống ổn định quy mô lớn",
    description: "CI/CD, Kubernetes, AWS/GCP, monitoring và tự động hoá hạ tầng.",
    skills: ["Linux", "Docker", "IaC", "Scripting"],
    averageSalary: "20–60 triệu/tháng (VN)",
    relatedSubjects: ["Tin học", "Toán"],
    opportunities: ["SaaS", "E-commerce", "Outsource"],
    workEnvironment: "Tech company, remote",
    studyPath: "CNTT · Cloud certification (AWS/Azure)",
  },
  {
    id: "ai-eng",
    name: "Kỹ sư AI / Học máy",
    tagline: "Dạy máy học từ dữ liệu",
    highlight: "Triển vọng cao",
    description: "Xây model ML, LLM application, computer vision, recommendation system.",
    skills: ["Python", "Toán", "Deep learning", "Experiment"],
    averageSalary: "25–80 triệu/tháng (VN)",
    relatedSubjects: ["Toán", "Tin học", "Tiếng Anh"],
    opportunities: ["AI startup", "Big tech", "Research"],
    workEnvironment: "Lab, product team, remote",
    studyPath: "CNTT · Toán · AI/ML specialization",
  },
  {
    id: "pm",
    name: "Quản lý sản phẩm",
    tagline: "Định hình sản phẩm người dùng yêu thích",
    description: "Research user, viết PRD, ưu tiên backlog, phối hợp design và engineering.",
    skills: ["Tư duy sản phẩm", "Giao tiếp", "Phân tích", "Leadership"],
    averageSalary: "20–70 triệu/tháng (VN)",
    relatedSubjects: ["Toán", "Ngữ văn", "Tin học"],
    opportunities: ["Tech product", "EdTech", "Fintech"],
    workEnvironment: "Startup, product company",
    studyPath: "CNTT/Kinh doanh · PM course + case study",
  },
  {
    id: "qa",
    name: "Kiểm thử phần mềm",
    tagline: "Đảm bảo chất lượng trước khi release",
    description: "Viết test case, manual/automation test, báo bug và theo dõi fix.",
    skills: ["Tỉ mỉ", "Logic", "Automation cơ bản", "Giao tiếp"],
    averageSalary: "10–30 triệu/tháng (VN)",
    relatedSubjects: ["Tin học", "Toán"],
    opportunities: ["Manual QA", "Automation", "QA lead"],
    workEnvironment: "Software company, outsource",
    studyPath: "CNTT · Khóa QA + Selenium/Cypress",
  },
  {
    id: "ba",
    name: "Phân tích nghiệp vụ",
    tagline: "Cầu nối giữa business và IT",
    description: "Thu thập yêu cầu, vẽ flow, viết spec và hỗ trợ triển khai phần mềm doanh nghiệp.",
    skills: ["Phân tích", "Documentation", "Workshop", "SQL cơ bản"],
    averageSalary: "15–40 triệu/tháng (VN)",
    relatedSubjects: ["Toán", "Tin học", "Kinh tế"],
    opportunities: ["Bank", "ERP", "Consulting"],
    workEnvironment: "Corporate IT, consulting firm",
    studyPath: "CNTT · Quản trị kinh doanh · CBAP (tuỳ mục tiêu)",
  },
  {
    id: "logistics",
    name: "Quản lý chuỗi cung ứng",
    tagline: "Hàng hoá đi đúng – đủ – nhanh",
    description: "Lập kế hoạch vận chuyển, kho bãi, inventory cho e-commerce và sản xuất.",
    skills: ["Tổ chức", "Excel", "Đàm phán", "Tối ưu chi phí"],
    averageSalary: "10–30 triệu/tháng (VN)",
    relatedSubjects: ["Toán", "Địa lý", "Kinh tế"],
    opportunities: ["E-commerce", "3PL", "Manufacturing"],
    workEnvironment: "Kho, văn phòng, cảng",
    studyPath: "Logistics · Quản trị chuỗi cung ứng",
  },
  {
    id: "agri",
    name: "Kỹ sư nông nghiệp",
    tagline: "Công nghệ cho nông trại hiện đại",
    description: "Cải tiến giống, tưới tiêu, smart farm và an toàn thực phẩm.",
    skills: ["Sinh học", "Quản lý", "IoT cơ bản", "Thực địa"],
    averageSalary: "8–25 triệu/tháng (VN)",
    relatedSubjects: ["Sinh học", "Hoá", "Địa lý"],
    opportunities: ["AgriTech", "Doanh nghiệp nông sản", "R&D"],
    workEnvironment: "Nông trại, lab, công ty phân bón",
    studyPath: "Nông nghiệp · Công nghệ thực phẩm",
  },
  {
    id: "env",
    name: "Chuyên gia môi trường",
    tagline: "Bảo vệ tài nguyên và ESG",
    highlight: "Xu hướng",
    description: "Đánh giá tác động môi trường, xử lý chất thải, báo cáo ESG cho doanh nghiệp.",
    skills: ["Hoá – Sinh", "Pháp luật môi trường", "Báo cáo", "Thực địa"],
    averageSalary: "10–30 triệu/tháng (VN)",
    relatedSubjects: ["Sinh học", "Hoá", "Địa lý"],
    opportunities: ["Consulting", "Manufacturing", "NGO"],
    workEnvironment: "Hiện trường, văn phòng, viện nghiên cứu",
    studyPath: "Môi trường · Quản lý tài nguyên",
  },
  {
    id: "energy",
    name: "Kỹ sư năng lượng tái tạo",
    tagline: "Điện mặt trời, gió và lưu trữ",
    description: "Thiết kế hệ thống solar/wind, tối ưu hiệu suất và vận hành trạm điện.",
    skills: ["Vật lý", "CAD", "An toàn", "Dự án"],
    averageSalary: "12–40 triệu/tháng (VN)",
    relatedSubjects: ["Vật lý", "Toán", "Hoá"],
    opportunities: ["Solar EPC", "Wind farm", "Energy storage"],
    workEnvironment: "Công trường, văn phòng kỹ thuật",
    studyPath: "Điện · Năng lượng · Mechanical",
  },
  {
    id: "pilot",
    name: "Phi công thương mại",
    tagline: "Lái máy bay chở khách và hàng hoá",
    highlight: "Đặc thù",
    description: "Điều khiển máy bay, tuân thủ an toàn hàng không và quy trình vận hành.",
    skills: ["Phản xạ", "Tiếng Anh", "Kỷ luật", "Spatial awareness"],
    averageSalary: "40–150+ triệu/tháng (tuỳ hãng)",
    relatedSubjects: ["Toán", "Vật lý", "Tiếng Anh"],
    opportunities: ["Hàng không Việt Nam", "Hãng quốc tế"],
    workEnvironment: "Buồng lái, lịch bay ca",
    studyPath: "Học viện hàng không · CPL/ATPL",
  },
  {
    id: "flight-att",
    name: "Tiếp viên hàng không",
    tagline: "An toàn và dịch vụ trên cabin",
    description: "Hướng dẫn an toàn, phục vụ hành khách và xử lý tình huống trên chuyến bay.",
    skills: ["Giao tiếp", "Tiếng Anh", "Ngoại hình chuyên nghiệp", "Ứng biến"],
    averageSalary: "15–40 triệu/tháng (tuỳ hãng)",
    relatedSubjects: ["Tiếng Anh", "GDCD"],
    opportunities: ["Hãng bay nội địa", "Quốc tế"],
    workEnvironment: "Cabin, sân bay, lịch bay",
    studyPath: "Khóa tiếp viên · Tiếng Anh ICAO",
  },
  {
    id: "police",
    name: "Công an / An ninh trật tự",
    tagline: "Giữ gìn pháp luật và an toàn xã hội",
    description: "Tuần tra, điều tra, bảo vệ an ninh cho cộng đồng theo quy định nhà nước.",
    skills: ["Kỷ luật", "Thể lực", "Pháp luật", "Ứng phó"],
    averageSalary: "Theo biên chế nhà nước",
    relatedSubjects: ["GDCD", "Lịch sử", "Thể dục"],
    opportunities: ["Công an phường", "Cảnh sát hình sự", "An ninh mạng (chuyên ngành)"],
    workEnvironment: "Hiện trường, trụ sở",
    studyPath: "Học viện CAND · Cao đẳng công an",
  },
  {
    id: "firefighter",
    name: "Lực lượng cứu hoả",
    tagline: "Ứng cứu khẩn cấp và an toàn cộng đồng",
    description: "Chữa cháy, cứu nạn, sơ tán và phòng cháy chữa cháy cho khu dân cư.",
    skills: ["Thể lực", "Phản xạ", "Làm việc nhóm", "Kỷ luật"],
    averageSalary: "Theo biên chế / lương công vụ",
    relatedSubjects: ["Thể dục", "Hoá", "GDCD"],
    opportunities: ["PCCC địa phương", "Công ty PCCC tư"],
    workEnvironment: "Trạm cứu hoả, hiện trường",
    studyPath: "Trung cấp PCCC · Huấn luyện chuyên ngành",
  },
  {
    id: "social-worker",
    name: "Công tác xã hội",
    tagline: "Hỗ trợ cộng đồng yếu thế",
    description: "Tư vấn, kết nối nguồn lực, hỗ trợ trẻ em, người già, người khuyết tật.",
    skills: ["Đồng cảm", "Lắng nghe", "Phối hợp", "Kiên nhẫn"],
    averageSalary: "7–18 triệu/tháng (VN)",
    relatedSubjects: ["GDCD", "Ngữ văn", "Sinh học"],
    opportunities: ["NGO", "Trung tâm xã hội", "Dự án cộng đồng"],
    workEnvironment: "Hiện trường, trung tâm, viện",
    studyPath: "Công tác xã hội · Tâm lý học",
  },
  {
    id: "event",
    name: "Tổ chức sự kiện",
    tagline: "Biến ý tưởng thành trải nghiệm live",
    description: "Lên concept, booking vendor, vận hành hội nghị, concert, activation brand.",
    skills: ["Tổ chức", "Đàm phán", "Sáng tạo", "Áp lực deadline"],
    averageSalary: "10–35 triệu/tháng (VN)",
    relatedSubjects: ["Ngữ văn", "Mỹ thuật", "Tiếng Anh"],
    opportunities: ["Event agency", "Corporate event", "Festival"],
    workEnvironment: "On-site, agency, freelance",
    studyPath: "Truyền thông · Quản trị sự kiện",
  },
  {
    id: "photo",
    name: "Nhiếp ảnh gia / Quay phim",
    tagline: "Ghi lại khoảnh khắc bằng hình ảnh",
    description: "Chụp ảnh cưới, sản phẩm, quay phim quảng cáo và social content.",
    skills: ["Composition", "Lightroom/Premiere", "Thẩm mỹ", "Edit"],
    averageSalary: "8–40+ triệu/tháng (freelance)",
    relatedSubjects: ["Mỹ thuật", "Tin học"],
    opportunities: ["Wedding", "Commercial", "Creator"],
    workEnvironment: "Studio, outdoor, freelance",
    studyPath: "Mỹ thuật · Khóa nhiếp ảnh + portfolio",
  },
  {
    id: "music",
    name: "Nhạc sĩ / Sản xuất âm nhạc",
    tagline: "Sáng tác và sản xuất âm thanh",
    description: "Sáng tác, thu âm, mix master, sản xuất nhạc cho artist và media.",
    skills: ["Nhạc lý", "DAW", "Sáng tạo", "Collaboration"],
    averageSalary: "Không cố định · 5–50+ triệu/tháng",
    relatedSubjects: ["Âm nhạc", "Tiếng Anh"],
    opportunities: ["Independent artist", "Studio", "Jingle/ads"],
    workEnvironment: "Studio, remote, live",
    studyPath: "Nhạc viện · Tự học DAW + portfolio",
  },
  {
    id: "actor",
    name: "Diễn viên / Dẫn chương trình",
    tagline: "Thể hiện cảm xúc trên sân khấu và màn ảnh",
    description: "Diễn xuất phim, kịch, dẫn chương trình, voice-over và quảng cáo.",
    skills: ["Diễn xuất", "Giao tiếp", "Ngoại ngữ", "Thể lực"],
    averageSalary: "Không cố định · theo dự án",
    relatedSubjects: ["Ngữ văn", "Âm nhạc", "GDCD"],
    opportunities: ["Phim", "Truyền hình", "MC sự kiện"],
    workEnvironment: "Set quay, sân khấu, studio",
    studyPath: "Sân khấu – Điện ảnh · Casting + demo reel",
  },
  {
    id: "sport-coach",
    name: "Huấn luyện viên thể thao",
    tagline: "Rèn luyện thể chất và tinh thần chiến thắng",
    description: "Huấn luyện kỹ thuật, chiến thuật, dinh dưỡng cơ bản cho vận động viên.",
    skills: ["Thể lực", "Motivation", "Kỹ thuật môn", "An toàn"],
    averageSalary: "8–30 triệu/tháng (VN)",
    relatedSubjects: ["Thể dục", "Sinh học"],
    opportunities: ["CLB", "Trường học", "Fitness center"],
    workEnvironment: "Sân vận động, phòng gym",
    studyPath: "Thể dục thể thao · Chứng chỉ HLV",
  },
  {
    id: "fitness",
    name: "Huấn luyện viên thể hình",
    tagline: "Thiết kế lộ trình tập luyện cá nhân",
    description: "Tư vấn dinh dưỡng cơ bản, hướng dẫn tập và theo dõi tiến độ khách hàng.",
    skills: ["Giải phẫu cơ bản", "Giao tiếp", "Motivation", "An toàn tập"],
    averageSalary: "10–35 triệu/tháng (có hoa hồng PT)",
    relatedSubjects: ["Sinh học", "Thể dục"],
    opportunities: ["Gym chain", "Freelance PT", "Online coach"],
    workEnvironment: "Phòng gym, studio, online",
    studyPath: "Chứng chỉ PT · Dinh dưỡng thể thao",
  },
  {
    id: "ecom",
    name: "Quản lý thương mại điện tử",
    tagline: "Bán hàng online đa kênh",
    description: "Vận hành shop Shopee/Lazada/TikTok Shop, ads, fulfillment và chăm sóc khách.",
    skills: ["Ads", "Data cơ bản", "CSKH", "Merchandising"],
    averageSalary: "10–35 triệu/tháng (VN)",
    relatedSubjects: ["Kinh tế", "Tin học", "Tiếng Anh"],
    opportunities: ["Brand in-house", "Seller lớn", "Agency"],
    workEnvironment: "Văn phòng, kho, remote",
    studyPath: "Marketing · Kinh doanh · On-job e-commerce",
  },
  {
    id: "supply-qc",
    name: "Kiểm soát chất lượng sản xuất",
    tagline: "Giữ chuẩn sản phẩm trước khi xuất xưởng",
    description: "Kiểm tra lô hàng, quy trình ISO, phân tích lỗi và cải tiến sản xuất.",
    skills: ["Tỉ mỉ", "Thống kê cơ bản", "Quy trình", "Báo cáo"],
    averageSalary: "8–22 triệu/tháng (VN)",
    relatedSubjects: ["Hoá", "Toán", "Vật lý"],
    opportunities: ["Electronics", "Garment", "F&B factory"],
    workEnvironment: "Nhà máy, lab QC",
    studyPath: "Công nghệ · QA/QC · ISO training",
  },
  {
    id: "bio-tech",
    name: "Kỹ thuật viên phòng thí nghiệm",
    tagline: "Thí nghiệm và nghiên cứu trong phòng lab",
    description: "Chạy mẫu, PCR, cell culture, hỗ trợ R&D dược và y sinh.",
    skills: ["Sinh học", "Tỉ mỉ", "Ghi chép lab", "An toàn"],
    averageSalary: "10–28 triệu/tháng (VN)",
    relatedSubjects: ["Sinh học", "Hoá", "Toán"],
    opportunities: ["Pharma lab", "Hospital lab", "Research institute"],
    workEnvironment: "Phòng lab, viện nghiên cứu",
    studyPath: "Sinh học · Công nghệ sinh học · Y sinh",
  },
  {
    id: "optometrist",
    name: "Kỹ thuật viên mắt",
    tagline: "Đo thị lực và tư vấn kính",
    description: "Khám thị lực, đo khúc xạ, tư vấn kính áp tròng và chăm sóc mắt cơ bản.",
    skills: ["Tỉ mỉ", "Giao tiếp", "Thiết bị chuyên dụng", "Tư vấn"],
    averageSalary: "8–20 triệu/tháng (VN)",
    relatedSubjects: ["Sinh học", "Vật lý"],
    opportunities: ["Chuỗi cửa hàng kính", "Bệnh viện mắt"],
    workEnvironment: "Cửa hàng kính, phòng khám",
    studyPath: "Kỹ thuật mắt · Cao đẳng y tế",
  },
  {
    id: "physio",
    name: "Vật lý trị liệu",
    tagline: "Phục hồi chức năng vận động",
    description: "Trị liệu chấn thương, rehab sau phẫu thuật, tư vấn bài tập phục hồi.",
    skills: ["Giải phẫu", "Kiên nhẫn", "Thực hành", "Giao tiếp"],
    averageSalary: "10–30 triệu/tháng (VN)",
    relatedSubjects: ["Sinh học", "Thể dục"],
    opportunities: ["Phòng khám", "Bệnh viện", "Sports club"],
    workEnvironment: "Clinic, gym rehab, bệnh viện",
    studyPath: "Vật lý trị liệu · Y khoa liên quan",
  },
  {
    id: "nutrition",
    name: "Chuyên gia dinh dưỡng",
    tagline: "Xây dựng chế độ ăn khoa học",
    description: "Tư vấn dinh dưỡng cá nhân, thực đơn bệnh lý, dinh dưỡng cộng đồng.",
    skills: ["Sinh học", "Tư vấn", "Lập kế hoạch", "Giao tiếp"],
    averageSalary: "8–25 triệu/tháng (VN)",
    relatedSubjects: ["Sinh học", "Hoá"],
    opportunities: ["Bệnh viện", "Spa/wellness", "Online coach"],
    workEnvironment: "Phòng khám, trung tâm, online",
    studyPath: "Dinh dưỡng · Công nghệ thực phẩm",
  },
  {
    id: "civil-servant",
    name: "Công chức / Viên chức nhà nước",
    tagline: "Phục vụ hành chính công",
    description: "Thực hiện nhiệm vụ hành chính, chính sách tại sở ban ngành và địa phương.",
    skills: ["Kỷ luật", "Văn bản", "Giao tiếp", "Tổ chức"],
    averageSalary: "Theo bậc lương công vụ",
    relatedSubjects: ["Ngữ văn", "Lịch sử", "GDCD"],
    opportunities: ["Sở ngành", "UBND", "Đơn vị sự nghiệp"],
    workEnvironment: "Cơ quan nhà nước",
    studyPath: "Đại học ngành liên quan · Thi công chức",
  },
  {
    id: "diplomat",
    name: "Ngoại giao / Quan hệ quốc tế",
    tagline: "Đại diện Việt Nam trên trường quốc tế",
    highlight: "Đặc thù",
    description: "Nghiên cứu chính sách, đàm phán, hỗ trợ công dân và quan hệ song phương.",
    skills: ["Tiếng Anh", "Lịch sử", "Đàm phán", "Viết"],
    averageSalary: "Theo biên chế ngoại giao",
    relatedSubjects: ["Tiếng Anh", "Lịch sử", "Địa lý"],
    opportunities: ["Bộ Ngoại giao", "Lãnh sự", "UN/NGO quốc tế"],
    workEnvironment: "Đại sứ quán, Bộ, hội nghị",
    studyPath: "Quan hệ quốc tế · Luật quốc tế · Thi tuyển ngoại giao",
  },
  {
    id: "startup",
    name: "Khởi nghiệp",
    tagline: "Tự xây dựng sản phẩm và doanh nghiệp",
    highlight: "Rủi ro cao – reward cao",
    description: "Tìm ý tưởng, validate thị trường, gọi vốn, tuyển team và scale startup.",
    skills: ["Leadership", "Bán hàng", "Học nhanh", "Chịu áp lực"],
    averageSalary: "Không cố định · equity + lương startup",
    relatedSubjects: ["Kinh tế", "Tin học", "Ngữ văn"],
    opportunities: ["Tech startup", "Social enterprise", "SME"],
    workEnvironment: "Startup office, remote, co-working",
    studyPath: "Bất kỳ ngành · Accelerator · Mentor",
  },
  {
    id: "blockchain",
    name: "Lập trình viên Blockchain",
    tagline: "Xây smart contract và ứng dụng phi tập trung",
    description: "Phát triển dApp, smart contract Solidity/Rust, tích hợp ví và on-chain data.",
    skills: ["Solidity", "Security mindset", "Crypto basics", "Backend"],
    averageSalary: "20–70 triệu/tháng (VN/global remote)",
    relatedSubjects: ["Tin học", "Toán", "Tiếng Anh"],
    opportunities: ["Crypto startup", "Remote global", "Security audit"],
    workEnvironment: "Remote, crypto startup",
    studyPath: "CNTT · Smart contract course + audit mindset",
  },
  {
    id: "iot-eng",
    name: "Kỹ sư IoT / Nhúng",
    tagline: "Kết nối thiết bị vật lý với internet",
    description: "Firmware, sensor, edge device cho smart home, industrial IoT, wearables.",
    skills: ["C/C++", "Electronics", "MQTT", "Debugging hardware"],
    averageSalary: "15–45 triệu/tháng (VN)",
    relatedSubjects: ["Tin học", "Vật lý", "Toán"],
    opportunities: ["Smart device", "Industrial", "Automotive"],
    workEnvironment: "Lab, factory, R&D",
    studyPath: "Điện tử · Embedded systems",
  },
  {
    id: "robotics",
    name: "Kỹ sư robot / Tự động hoá",
    tagline: "Robot phục vụ sản xuất và đời sống",
    highlight: "Tương lai",
    description: "Thiết kế cánh tay robot, vision system, PLC và tự động hoá dây chuyền.",
    skills: ["Mechanical", "Programming", "Control theory", "CAD"],
    averageSalary: "15–50 triệu/tháng (VN)",
    relatedSubjects: ["Toán", "Vật lý", "Tin học"],
    opportunities: ["Manufacturing", "Warehouse automation", "R&D"],
    workEnvironment: "Factory, lab, tech company",
    studyPath: "Cơ khí · Mechatronics · Robotics",
  },
];
