export const CAREER_FIELD_IDS = [
  "tech",
  "health",
  "business",
  "creative",
  "engineering",
  "education",
  "service",
  "law-gov",
] as const;

export type CareerFieldId = (typeof CAREER_FIELD_IDS)[number];

export const CAREER_FIELD_LABELS: Record<CareerFieldId, string> = {
  tech: "Công nghệ & IT",
  health: "Y tế & Sức khỏe",
  business: "Kinh doanh & Tài chính",
  creative: "Sáng tạo & Truyền thông",
  engineering: "Kỹ thuật & Sản xuất",
  education: "Giáo dục & Xã hội",
  service: "Du lịch & Dịch vụ",
  "law-gov": "Pháp luật & Hành chính",
};

const FIELD_BY_CAREER_ID: Record<string, CareerFieldId> = {
  se: "tech",
  ux: "creative",
  da: "tech",
  mk: "business",
  med: "health",
  teacher: "education",
  law: "law-gov",
  arch: "engineering",
  nurse: "health",
  mech: "engineering",
  creator: "creative",
  account: "business",
  "civil-eng": "engineering",
  "elec-eng": "engineering",
  pharm: "health",
  dentist: "health",
  vet: "health",
  psych: "health",
  journalist: "creative",
  translator: "creative",
  hr: "business",
  sales: "business",
  finance: "business",
  banker: "business",
  "real-estate": "business",
  chef: "service",
  hotel: "service",
  fashion: "creative",
  interior: "creative",
  "game-dev": "tech",
  "game-art": "creative",
  cybersec: "tech",
  devops: "tech",
  "ai-eng": "tech",
  pm: "tech",
  qa: "tech",
  ba: "tech",
  logistics: "business",
  agri: "engineering",
  env: "engineering",
  energy: "engineering",
  pilot: "service",
  "flight-att": "service",
  police: "law-gov",
  firefighter: "law-gov",
  "social-worker": "education",
  event: "creative",
  photo: "creative",
  music: "creative",
  actor: "creative",
  "sport-coach": "service",
  fitness: "service",
  ecom: "business",
  "supply-qc": "engineering",
  "bio-tech": "health",
  optometrist: "health",
  physio: "health",
  nutrition: "health",
  "civil-servant": "law-gov",
  diplomat: "law-gov",
  startup: "business",
  blockchain: "tech",
  "iot-eng": "tech",
  robotics: "engineering",
};

export function getCareerField(careerId: string): CareerFieldId {
  return FIELD_BY_CAREER_ID[careerId] ?? "tech";
}
